runtime: python27
api_version: 1
threadsafe: true

builtins:
- appstats: on

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: .*
  script: main.app

env_variables:
  PASSWORD: "password"
  SECRET_KEY: "change-this-please"
  S3_LINK_TTL: s3-link-ttl-in-seconds
  CACHE_TTL: memcache-page-ttl-in-seconds
  BUCKET: "s3-bucket-name"
  ACCESS_KEY: "aws-access-key"
  SECRET_ACCESS_KEY: "aws-secret-access-key"
